### ISSUE TITLE
Support Linux Nightly Build for Pip

### ISSUE THREAD

**Issue by mshawcroft** [tlc-pack/tlcpack#33]
Just noticed the nice form on https://tlcpack.ai but noticed that for pip, linux, no-cuda the form points to "build from source instruction" rather than recommending "pip install", switching to "Mac" and it does recommend pip install.  This is a bit surprising, any idea what's gone wrong?

**Comment by mshawcroft** [comment]
Maybe this isn't the write forum to discuss https://tlcpack.ai/, in which case please redirect me...

**Comment by tqchen** [comment]
This is simply because we haven't yet work on the workflow for linux. It be updated once @icemelon9 updates the linux wheel script

**Comment by leandron** [comment]
@tqchen @icemelon9 do you think we could use something like https://github.com/RalfG/python-wheels-manylinux-build to trigger GitHub actions in a manylinux environment? Or do you have something else in mind to solve this issue?

**Comment by tqchen** [comment]
@leandron  the technical solutions are as follows:


- We should be able to directly reuse the our current docker manylinux image https://github.com/tlc-pack/tlcpack/blob/main/docker/Dockerfile.package-cu102 
- Reuse recipes like https://github.com/tlc-pack/tlcpack/blob/main/.github/workflows/conda_gpu_nigthly.yaml#L47 to run the job in the docker environment
- Run the build script same as our previous ones.

I believe the delay is mainly due to @icemelon9 being busy and not able to get to these steps. My guess is that they would cost about a few days of work. Please let me know if  you are interested in helping out.

**Comment by tqchen** [comment]
gentle ping @leandron @icemelon9

**Comment by hogepodge** [comment]
I'm starting take a look at this issue and will see if we can enable the builds soon.

**Comment by hogepodge** [comment]
These two patches are the first steps in supporting Linux Nightly Pip
https://github.com/tlc-pack/tlcpack/pull/43
https://github.com/tlc-pack/tlcpack/pull/44

Once these land, I can send up a workflow patch that build nightly against the main branch. Stable won't build, as Ethos driver is incompatible with it.

**Comment by tqchen** [comment]
linux nightly is now available
